# Generated by Django 4.1 on 2022-08-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('created_at',), 'verbose_name': 'Белье', 'verbose_name_plural': 'Белье'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
