# Generated by Django 4.1 on 2022-08-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogshop', '0002_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
    ]
