version: '3.1'

services:

  db:
    image: postgres
    container_name: magazin
    restart: always
    environment:
      POSTGRES_PASSWORD: 658941
      POSTGRES_USER: dima
      POSTGRES_DB: magazin
      PGDATA: /home/django-site/test_shop/siteblog
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "54321:5432"
